import Quiz from "../models/Quiz.model.js";
import Question from "../models/Question.model.js";
import QuizResult from "../models/QuizResult.model.js";
import Lesson, { QUIZ_STATUS } from "../models/Lesson.model.js";
import { ApiError } from "../utils/ApiError.js";
import { lessonService } from "./lesson.service.js";
import { pdfService } from "./pdf.service.js";
import { mlClient } from "./mlClient.js";
import config from "../config/config.js";

function normalizeQuestion(question, index) {
  const questionText = String(question?.questionText || "").trim();
  const options = Array.isArray(question?.options)
    ? question.options.map((option) => String(option || "").trim())
    : [];
  const correctAnswerIndex = Number.parseInt(question?.correctAnswerIndex, 10);

  if (!questionText) {
    throw ApiError.badRequest(`Question ${index + 1} needs text`);
  }
  if (options.length !== 4 || options.some((option) => !option)) {
    throw ApiError.badRequest(`Question ${index + 1} must have exactly 4 non-empty options`);
  }
  if (!Number.isInteger(correctAnswerIndex) || correctAnswerIndex < 0 || correctAnswerIndex > 3) {
    throw ApiError.badRequest(`Question ${index + 1} has an invalid correct answer index`);
  }

  return { questionText, options, correctAnswerIndex };
}

export const quizService = {
  // Fire-and-forget: called right after a lesson PDF is uploaded so the quiz is
  // already generated by the time a student completes the lesson, instead of
  // making the first student wait ~10s. Never throws - failures are recorded on
  // the Lesson doc (quizStatus/quizError) for the lessons list UI to surface.
  async generateInBackground(lessonId) {
    await Lesson.findByIdAndUpdate(lessonId, {
      quizStatus: QUIZ_STATUS.GENERATING,
      $unset: { quizError: 1 },
    });

    try {
      // getOrGenerateForLesson reuses an existing Quiz doc if one is present, so
      // callers that mean "start over" (regenerate-quiz, retry-after-failure,
      // legacy pending lessons) need the old one cleared first or they'd just
      // get the stale quiz back unchanged.
      await lessonService.clearQuiz(lessonId);
      await this.getOrGenerateForLesson(lessonId);
      await Lesson.findByIdAndUpdate(lessonId, { quizStatus: QUIZ_STATUS.READY });
    } catch (err) {
      await Lesson.findByIdAndUpdate(lessonId, {
        quizStatus: QUIZ_STATUS.FAILED,
        quizError: err.message,
      });
    }
  },

  // One quiz is generated per lesson (shared across the class).
  async getOrGenerateForLesson(lessonId) {
    let quiz = await Quiz.findOne({ lesson: lessonId });
    if (quiz) {
      const questions = await Question.find({ quiz: quiz._id });
      return { quiz, questions };
    }

    const lesson = await lessonService.getById(lessonId);
    const lessonText = await lessonService.extractedTextFor(lesson, pdfService);

    const generated = await mlClient.generateQuiz({
      lessonText,
      numQuestions: config.quiz.questionCount,
    });

    if (!Array.isArray(generated) || generated.length === 0) {
      throw new ApiError(502, "AI quiz generation returned no questions");
    }

    quiz = await Quiz.create({ lesson: lessonId });
    const questions = await Question.insertMany(
      generated.map((q) => ({
        quiz: quiz._id,
        questionText: q.questionText,
        options: q.options,
        correctAnswerIndex: q.correctAnswerIndex,
      }))
    );

    return { quiz, questions };
  },

  async getQuizForLesson(lessonId) {
    const quiz = await Quiz.findOne({ lesson: lessonId });
    if (!quiz) {
      return null;
    }

    const questions = await Question.find({ quiz: quiz._id });
    return { quiz, questions };
  },

  async replaceQuizQuestions(lessonId, questions) {
    const quiz = await Quiz.findOne({ lesson: lessonId });
    if (!quiz) {
      throw ApiError.notFound("Quiz not found for this lesson");
    }

    // Editing deletes and re-inserts Question docs (new _ids), which would
    // orphan any QuizResult.answers[].question already pointing at the old
    // ones - their per-question review would silently show every answer as
    // wrong. Block edits once someone has submitted instead of corrupting it.
    const hasSubmissions = await QuizResult.exists({ quiz: quiz._id });
    if (hasSubmissions) {
      throw ApiError.conflict(
        "This quiz already has student submissions and can no longer be edited"
      );
    }

    const normalizedQuestions = (Array.isArray(questions) ? questions : []).map(normalizeQuestion);
    if (!normalizedQuestions.length) {
      throw ApiError.badRequest("At least one question is required");
    }

    await Question.deleteMany({ quiz: quiz._id });
    const insertedQuestions = await Question.insertMany(
      normalizedQuestions.map((question) => ({
        quiz: quiz._id,
        questionText: question.questionText,
        options: question.options,
        correctAnswerIndex: question.correctAnswerIndex,
      }))
    );

    await Lesson.findByIdAndUpdate(lessonId, {
      quizStatus: QUIZ_STATUS.READY,
      $unset: { quizError: 1 },
    });

    return { quiz, questions: insertedQuestions };
  },

  // Answers key is withheld until after submission.
  toStudentFacing(questions) {
    return questions.map((q) => ({
      id: q._id,
      questionText: q.questionText,
      options: q.options,
    }));
  },

  toTeacherFacing(questions) {
    return questions.map((q) => ({
      id: q._id,
      questionText: q.questionText,
      options: q.options,
      correctAnswerIndex: q.correctAnswerIndex,
    }));
  },

  // Powers the post-submit review: each question alongside what the student
  // picked and whether it was right, so the quiz page can show a right/wrong
  // breakdown instead of just the aggregate score.
  toReviewFacing(questions, result) {
    const answerByQuestion = new Map(
      result.answers.map((a) => [a.question.toString(), a])
    );
    return questions.map((q) => {
      const answer = answerByQuestion.get(q._id.toString());
      return {
        id: q._id,
        questionText: q.questionText,
        options: q.options,
        correctAnswerIndex: q.correctAnswerIndex,
        selectedIndex: answer?.selectedIndex,
        isCorrect: answer?.isCorrect ?? false,
      };
    });
  },

  async submit({ quizId, studentId, answers }) {
    const existing = await QuizResult.findOne({ quiz: quizId, student: studentId });
    if (existing) throw ApiError.conflict("You have already submitted this quiz");

    const questions = await Question.find({ quiz: quizId });
    if (!questions.length) throw ApiError.notFound("Quiz not found");

    const answerByQuestion = new Map(answers.map((a) => [a.questionId, a.selectedIndex]));

    const gradedAnswers = questions.map((q) => {
      const selectedIndex = answerByQuestion.get(q._id.toString());
      if (selectedIndex === undefined) {
        throw ApiError.badRequest(`Missing answer for question ${q._id}`);
      }
      return {
        question: q._id,
        selectedIndex,
        isCorrect: selectedIndex === q.correctAnswerIndex,
      };
    });

    const score = gradedAnswers.filter((a) => a.isCorrect).length;

    return QuizResult.create({
      quiz: quizId,
      student: studentId,
      answers: gradedAnswers,
      score,
      totalQuestions: questions.length,
    });
  },

  async resultsForStudentInQuizzes(quizIds, studentId) {
    return QuizResult.find({ quiz: { $in: quizIds }, student: studentId });
  },

  // Powers the student-facing Results page: every quiz they've taken in a class,
  // with the lesson title attached so it reads as "Chapter 3 quiz: 4/5" rather
  // than a bare quiz id.
  async listResultsForStudentInClass(classId, studentId) {
    const lessons = await Lesson.find({ class: classId }, "_id title");
    const lessonTitleById = new Map(lessons.map((l) => [l._id.toString(), l.title]));

    const quizzes = await Quiz.find({ lesson: { $in: lessons.map((l) => l._id) } });
    const lessonTitleByQuizId = new Map(
      quizzes.map((q) => [q._id.toString(), lessonTitleById.get(q.lesson.toString())])
    );

    const results = await QuizResult.find({
      quiz: { $in: quizzes.map((q) => q._id) },
      student: studentId,
    }).sort({ submittedAt: -1 });

    return results.map((r) => ({
      ...r.toObject(),
      lessonTitle: lessonTitleByQuizId.get(r.quiz.toString()) || "Lesson",
    }));
  },
};
